services:
  frontend:
    image: ghcr.io/dream-merchants-vit/my-bid-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./.env.frontend

  backend:
    image: ghcr.io/dream-merchants-vit/my-bid-backend:latest
    ports:
      - "3001:3001"
    env_file:
      - ./.env.backend
